services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: asteroid-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: asteroid-server
    environment:
      - PORT=5000
      - CLIENT_ORIGIN=http://localhost:3000
      - FASTAPI_URL=http://backend:8000
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_MESSAGING_SID=${TWILIO_MESSAGING_SID}
      - ALERT_PHONE=${ALERT_PHONE}
    depends_on:
      - backend
    ports:
      - "5000:5000"
    restart: unless-stopped
    env_file:
      - ./backend/.env   # reuse your existing .env with Twilio values

  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asteroid-client
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - REACT_APP_API_BASE=http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: unless-stopped
