services:
  - type: web
    name: backend-service
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    autoDeploy: true

  - type: web
    name: node-server
    env: docker
    dockerfilePath: ./server/Dockerfile
    plan: free
    autoDeploy: true
