services:
  # ======================= FRONTEND (React, root /src) =======================
  - type: web
    name: frontend
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    # SPA routing so client-side routes work
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      # Point the React app to the Node service (public URL is derived from service name)
      - key: REACT_APP_API_BASE_URL
        value: https://node-server.onrender.com
      - key: REACT_APP_SOCKET_URL
        value: https://node-server.onrender.com

  # ======================= BACKEND (FastAPI) =======================
  - type: web
    name: backend-service
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      # Allow the hosted frontend and node-server to call FastAPI
      - key: CORS_ORIGINS
        value: https://frontend.onrender.com,https://node-server.onrender.com
      # --- Twilio (prompted securely at deploy time) ---
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_MESSAGING_SERVICE_SID
        sync: false
      - key: ALERT_PHONE
        sync: false

  # ======================= NODE / SOCKET.IO (proxy + alerts) =======================
  - type: web
    name: node-server
    runtime: docker
    dockerfilePath: ./server/Dockerfile
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      # Frontend origin(s) for CORS (add more origins with commas if needed)
      - key: CLIENT_ORIGIN
        value: https://frontend.onrender.com
      # Where Node calls the FastAPI backend
      - key: FASTAPI_URL
        value: https://backend-service.onrender.com
      # --- Twilio (prompted securely at deploy time) ---
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_MESSAGING_SERVICE_SID
        sync: false
      - key: ALERT_PHONE
        sync: false
